SikIndustries\Bundles\TrobaUserBundle\Entity\User:
  constraints:
    - Scandio\TrobaBridgeBundle\Validator\Constraints\DuplicateEntity:
        field: username
        groups: [registration]
    - Scandio\TrobaBridgeBundle\Validator\Constraints\DuplicateEntity:
        field: email
        groups: [registration]
  properties:
    email:
      - NotBlank: ~
      - Email: ~
    username:
      - Length: {min: 6, max: 255}
      - NotBlank: ~
    password:
      - Length: {min: 6 }
      - NotBlank: ~