SikIndustries\Bundles\UserBundle\Entity\User:
  properties:
    email:
      - NotBlank: ~
      - Email: ~
    username:
      - Length: {min: 6, max: 255}
      - NotBlank: ~
    password:
      - Length: {min: 6 }
      - NotBlank: ~